### ISSUE TITLE
Task3

### ISSUE THREAD

**Issue by AntonZamyatin** [AntonZamyatin/bio-python-course#3]
solved

**Comment by YakutovDmitriy** [comment]
Hi!

All functions except `repeatntimes` are ok.

This functions is hard one. The problem is the following. When you are yielding from iterator once, this iterator becomes empty if it is finite. And when you aer yielding from this iterator second time there is nothing to yield. 

Also you should stylistic mistake: it is necessary to wrap binary operators with spaces: `x*y -> x * y`

**Comment by AntonZamyatin** [comment]
About `repeatntimes`. Ithink it's working:
`>>> list(task3.repeatntimes([1,2,3],4))
[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]` 
`>>> list(task3.repeatntimes(range(3),4))
[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]`
or i dont understand you.

About code style. Flake8 linter doesn't see troubles with no spaces between args and  `*` and `**` operators. Do you know how fix it?

**Comment by YakutovDmitriy** [comment]
try, for example, such code:
`repeatntimes(changecase('word'), 2)`
The result is `'W', 'O', 'R', 'D'`, but it should repeat it twice.

Code style. Actually I don't know how to use python linters, I just know some rules :(

**Comment by AntonZamyatin** [comment]
about rules: http://www.python.org/dev/peps/pep-0008/#other-recommendations

**Comment by AntonZamyatin** [comment]
`repeatntimes` fixed

**Comment by YakutovDmitriy** [comment]
Good!

**Comment by AntonZamyatin** [comment]
number or digit .
5 task solved

**Comment by AntonZamyatin** [comment]
All solved. `subpalindrome` fixed

**Comment by AntonZamyatin** [comment]
Please can you give more information?
