### ISSUE TITLE
task4

### ISSUE THREAD

**Issue by AntonZamyatin** [AntonZamyatin/bio-python-course#4]
before genbin

**Comment by YakutovDmitriy** [comment]
At first glance they are ok
I will check them precisely a bit later

**Comment by AntonZamyatin** [comment]
Task4 solved

**Comment by YakutovDmitriy** [comment]
Almost everything is ok. The exceptions:

* `recurrent`. You have other name of this function: `reccurent`. It is partly my fault because I misprinted in a such way in several places of homework description. Please fix it
* `drawborders`. You have `n - 2` calls of `drawborders(n - 2)`. Python can't know the fact that this function always return the same result. So every such call produces very big tree of recursive calls. E.g. if `n = 50`. The first calling produces `48` cell. Every such call produces `46` more calls and so on. As a result you have about `48 * 46 * 44 * ... * 4 * 2` calls. This is pretty large number, your function works very slow. You can make only one recursive call and save a result in some variable.
* `concatnumbers`. A test: `a = 10, b = 101`. You result is `1011`. Please fix it. Actually there is a way to write this function using recursion approach without creating strings and knowing lengths of these numbers. A hint: Try to cut the last digit of `b`, not the first. As in `digitsum`

Some more notes:

* It will be good to remove all prints from your functions. This print is a side effect which is not expected by the user of this module
* You can optimize functions `genbinarystrings` and `abacaba` in a way like in function `drawborders`. It is not critical in these functions, but they will work a little faster.

**Comment by YakutovDmitriy** [comment]
Good!
